### ISSUE TITLE
Error on 0.8.6

### ISSUE THREAD

**Issue by mech-tools** [HadaIonut/Foundry-SceneDefaults#1]
Hello,

When addind a new scene with default declared, I get this error:
![image](https://user-images.githubusercontent.com/1687854/122649835-2e476b80-d130-11eb-82ab-abc962beb959.png)

Also the new scene is not initialized with default settings previously stored.

**Comment by HadaIonut** [comment]
Hey so I cannot replicate your error, it would be useful if you could run the following command in the console and give me a picture of what it displays. `game?.settings?.get('sceneDefaults', 'defaultSettings');`

The output should look something like this:
![image](https://user-images.githubusercontent.com/29940738/122664126-0bf13480-d1a8-11eb-8582-f2ecdbbd7aaf.png)

**Comment by mech-tools** [comment]
Couldn't reproduce the issue.
I'm quite positive I saw the button to save the defaults in a scene configuration rather than in the module configuration window. And that is by saving default from there that I got the issue.
Now that I use the module configuration window as intended, I don't have issues.

**Comment by HadaIonut** [comment]
The save default button should be in the scene configuration. My module does not have anything into the module settings window. 

But if I remember correctly there is another module that has the save configs thing in the module settings. Maybe you have both modules installed?
This is the foundry page for the other module is this one https://foundryvtt.com/packages/scene-defaults/

**Comment by mech-tools** [comment]
Gosh, you're right, two modules, same name. Must have been the other module!

**Comment by HadaIonut** [comment]
Yeah, we even released them almost at the same time. It wasn't even intentional. 

I'll close this issue, if you have any other problems please open another issue

**Comment by mech-tools** [comment]
@HadaIonut using you module. I get this after created a scene

![image](https://user-images.githubusercontent.com/1687854/122667767-d4d55000-d1b4-11eb-9100-c5839928a67d.png)
