### ISSUE TITLE
[Request] Scene Templates

### ISSUE THREAD

**Issue by MelvinMcSnatch** [HadaIonut/Foundry-SceneDefaults#2]
It would be really handy to be able to set up different scene configurations to choose from. Any possibility this module could be expanded to do that?

**Comment by HadaIonut** [comment]
Hello, I have worked on this today and the feature will be ready tomorrow. I will post another message here when I have released the update

**Comment by HadaIonut** [comment]
I have released update 1.0.3 with this feature
